FIND_PATH(OTF2_INCLUDE_DIRS otf2/otf2.h
    $ENV{HOME}/opt/include
)

FIND_LIBRARY(OTF2_LIBRARIES otf2
    $ENV{HOME}/opt/lib
)


FIND_PACKAGE_HANDLE_STANDARD_ARGS(OTF2
	FAIL_MESSAGE "Couldn't find OTF2 library."
	REQUIRED_VARS OTF2_INCLUDE_DIRS OTF2_LIBRARIES
	)

