FIND_PATH(MUSTER_INCLUDE_DIRS kmedoids.h
    $ENV{HOME}/opt/include
    $ENV{HOME}/opt/muster/include
)

FIND_LIBRARY(MUSTER_LIBRARIES muster
    $ENV{HOME}/opt/lib
    $ENV{HOME}/opt/muster/lib
)


FIND_PACKAGE_HANDLE_STANDARD_ARGS(MUSTER
	FAIL_MESSAGE "Couldn't find Muster."
	REQUIRED_VARS MUSTER_INCLUDE_DIRS MUSTER_LIBRARIES
	)

