IF (NOT DEFINED OTF2_FOUND)
    SET (OTF2_FOUND FALSE)
ENDIF()

FIND_PATH(OTF2_INCLUDE_DIR otf2/otf2.h
    ${HOME}/opt/include
    /usr/include
)

FIND_LIBRARY(OTF2_LIBRARIES otf2
    ${HOME}/opt/lib
    /usr/lib
)

IF (OTF2_INCLUDE_DIR AND OTF2_LIBRARIES)
    SET(OTF2_FOUND TRUE)
    IF (CMAKE_VERBOSE_MAKEFILE)
	MESSAGE("Using OTF2_INCLUDE_DIR = " ${OTF2_INCLUDE_DIR})
	MESSAGE("Using OTF2_LIBRARIES = " ${OTF2_LIBRARIES})
    ENDIF()
ENDIF()
