IF (NOT DEFINED MUSTER_FOUND)
    SET (MUSTER_FOUND FALSE)
ENDIF()

FIND_PATH(MUSTER_INCLUDE_DIR kmedoids.h
    ${CMAKE_SOURCE_DIR}
    ${HOME}/opt/include
    /usr/include
)

FIND_LIBRARY(MUSTER_LIBRARIES muster
    ${CMAKE_SOURCE_DIR}
    ${HOME}/opt/lib
    /usr/lib
)

IF (MUSTER_INCLUDE_DIR AND MUSTER_LIBRARIES)
    SET(MUSTER_FOUND TRUE)
    IF (CMAKE_VERBOSE_MAKEFILE)
	MESSAGE("Using MUSTER_INCLUDE_DIR = " ${MUSTER_INCLUDE_DIR})
	MESSAGE("Using MUSTER_LIBRARIES = " ${MUSTER_LIBRARIES})
    ENDIF()
ENDIF()
